In [ ]:
#pip install scikit-learn pandas

Requirement already satisfied: scikit-learn in c:\users\sabin\miniconda3\lib\site-packages (1.7.1)
Requirement already satisfied: pandas in c:\users\sabin\miniconda3\lib\site-packages (2.3.1)
Requirement already satisfied: numpy>=1.22.0 in c:\users\sabin\miniconda3\lib\site-packages (from scikit-learn) (2.3.2)
Requirement already satisfied: scipy>=1.8.0 in c:\users\sabin\miniconda3\lib\site-packages (from scikit-learn) (1.16.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\sabin\miniconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\sabin\miniconda3\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sabin\miniconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\sabin\miniconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sabin\miniconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\sabin\miniconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

In [4]:
from sklearn.datasets import load_diabetes
diabetes = load_diabetes()

df = pd.DataFrame(data=diabetes.data, columns=diabetes.feature_names)

In [7]:
df
df.info()
df.describe()
df.corr()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
dtypes: float64(10)
memory usage: 34.7 KB

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
age,1.000000,0.173737,0.185085,0.335428,0.260061,0.219243,-0.075181,0.203841,0.270774,0.301731
sex,0.173737,1.000000,0.088161,0.241010,0.035277,0.142637,-0.379090,0.332115,0.149916,0.208133
bmi,0.185085,0.088161,1.000000,0.395411,0.249777,0.261170,-0.366811,0.413807,0.446157,0.388680
bp,0.335428,0.241010,0.395411,1.000000,0.242464,0.185548,-0.178762,0.257650,0.393480,0.390430
s1,0.260061,0.035277,0.249777,0.242464,1.000000,0.896663,0.051519,0.542207,0.515503,0.325717
s2,0.219243,0.142637,0.261170,0.185548,0.896663,1.000000,-0.196455,0.659817,0.318357,0.290600
s3,-0.075181,-0.379090,-0.366811,-0.178762,0.051519,-0.196455,1.000000,-0.738493,-0.398577,-0.273697
s4,0.203841,0.332115,0.413807,0.257650,0.542207,0.659817,-0.738493,1.000000,0.617859,0.417212
s5,0.270774,0.149916,0.446157,0.393480,0.515503,0.318357,-0.398577,0.617859,1.000000,0.464669
s6,0.301731,0.208133,0.388680,0.390430,0.325717,0.290600,-0.273697,0.417212,0.464669,1.000000

In [ ]:
X = df.drop(columns='s6')
y = df['s6']
X,y

(          age       sex       bmi        bp        s1        s2        s3  \
 0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401
 1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412
 2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356
 3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038
 4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142
 ..        ...       ...       ...       ...       ...       ...       ...
 437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674
 438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674
 439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993
 440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674
 441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816

            s4        s5
 0   -0.002592  0.019907
 1   -0.039493 -0.068332
 2   -0.002592  0.002861
 3    0.034309  0.022688
 4   -0.002592 -0.031988
 ..        ...       ...
 437 -0.002592  0.031193
 438  0.034309 -0.018114
 439 -0.011080 -0.046883
 440  0.026560  0.044529
 441 -0.039493 -0.004222

 [442 rows x 9 columns],
 0     -0.017646
 1     -0.092204
 2     -0.025930
 3     -0.009362
 4     -0.046641
          ...
 437    0.007207
 438    0.044485
 439    0.015491
 440   -0.025930
 441    0.003064
 Name: s6, Length: 442, dtype: float64)

In [19]:
from sklearn.model_selection import train_test_split

#Create Train and Test Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =0.2)
X_train

,age,sex,bmi,bp,s1,s2,s3,s4,s5
70,-0.001882,-0.044642,-0.069797,-0.012556,-0.000193,-0.009143,0.070730,-0.039493,-0.062917
75,-0.009147,0.050680,-0.030996,-0.026328,-0.011201,-0.001001,-0.021311,-0.002592,0.006207
61,-0.041840,0.050680,0.004572,-0.053870,-0.044223,-0.027305,-0.080217,0.071210,0.036644
234,0.045341,-0.044642,0.039062,0.045972,0.006687,-0.024174,0.008142,-0.012556,0.064328
72,0.063504,0.050680,-0.004050,-0.012556,0.103003,0.048790,0.056003,-0.002592,0.084492
...,...,...,...,...,...,...,...,...,...
372,-0.027310,0.050680,-0.023451,-0.015999,0.013567,0.012778,0.026550,-0.002592,-0.010903
135,-0.005515,-0.044642,0.056307,-0.036656,-0.048351,-0.042963,-0.072854,0.037999,0.050782
332,0.030811,-0.044642,0.104809,0.076958,-0.011201,-0.011335,-0.058127,0.034309,0.057108
17,0.070769,0.050680,0.012117,0.056301,0.034206,0.049416,-0.039719,0.034309,0.027364
284,0.041708,0.050680,-0.022373,0.028758,-0.066239,-0.045155,-0.061809,-0.002592,0.002861

## Create & Train Model
model = LinearRegression() model.fit(X_train, y_train)
## Predict
y_predicted = model.predict(X_test)
## Evaluate Model Performance
MAE MSE RMSE = root_mean_squared_error(y_predicted, y_test)

In [20]:
#Ridge
from sklearn.linear_model import Ridge

ridge_model = Ridge(alpha = 0.1)

ridge_model.fit(X_train, y_train)
ridge_model.coef_

array([ 0.10492729,  0.07908596,  0.15381894,  0.14773473,  0.05969667,
       -0.00261858, -0.01048572,  0.1020802 ,  0.20864762])

In [21]:
y_predicted = ridge_model.predict(X_test)
y_predicted

array([-0.01925375, -0.00569228, -0.03433392,  0.03028304, -0.00796198,
       -0.00212679, -0.04244696, -0.01117115,  0.00506004, -0.03356811,
       -0.00334646,  0.00696065,  0.02067434,  0.01633738,  0.00080503,
        0.01230909, -0.000932  , -0.01013843,  0.0405673 ,  0.01949871,
       -0.06125364,  0.01335733, -0.04115313,  0.02651815, -0.02009643,
        0.04047187, -0.03877504, -0.05081748,  0.00230499, -0.0311516 ,
       -0.0006562 ,  0.01211242,  0.00504287, -0.02213524, -0.01993452,
        0.03278186, -0.0239996 , -0.02981293, -0.01140245,  0.04689816,
       -0.00148339,  0.04833066, -0.03528039, -0.01910946,  0.00298117,
       -0.01303656, -0.00277837, -0.00232181, -0.03337412,  0.02096699,
       -0.02335929,  0.02691121, -0.03969032,  0.01930604,  0.00644387,
       -0.01476274, -0.05850112,  0.04975566,  0.03331025, -0.05338788,
       -0.02319568,  0.01598129,  0.021179  ,  0.02437593,  0.00104574,
        0.00356551, -0.03096338, -0.01442701,  0.03834486,  0.01619524,
        0.04785749,  0.00682267, -0.03993853, -0.05497311, -0.01213935,
       -0.02589867, -0.01620469, -0.02285933,  0.00837346, -0.0406184 ,
        0.00083681,  0.01572645,  0.005808  , -0.00384137,  0.01558517,
        0.02035311,  0.01491276, -0.008941  , -0.00781729])

In [22]:
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, mean_squared_error, r2_score
ridge_mae = mean_absolute_error(y_predicted, y_test)
ridge_mse = mean_squared_error(y_predicted, y_test)
ridge_rmse = root_mean_squared_error(y_predicted, y_test)



ridge_mae, ridge_mse, ridge_rmse

(0.027816250371136008, 0.0013248761879521955, 0.03639884871740033)

In [27]:
alpha_values = [0.01,0.1,0.25,0.5,1.0]
for alpha_value in alpha_values:

    ridge_model = Ridge(alpha = alpha_value)
    
    ridge_model.fit(X_train,y_train)

    y_predicted = ridge_model.predict(X_test)

    ridge_mae = mean_absolute_error(y_predicted, y_test)
    ridge_mse = mean_squared_error(y_predicted, y_test)
    ridge_rmse = root_mean_squared_error(y_predicted, y_test)
    print (f"ridge name:{ridge_mae} , ridge_mse: {ridge_mse}, ridge_rmse: {ridge_rmse}")

ridge name:0.028182307973677365 , ridge_mse: 0.0013473473140668021, ridge_rmse: 0.03670622990810691
ridge name:0.027816250371136008 , ridge_mse: 0.0013248761879521955, ridge_rmse: 0.03639884871740033
ridge name:0.027412446098375766 , ridge_mse: 0.0013023332274085377, ridge_rmse: 0.03608785429210966
ridge name:0.027129104249763877 , ridge_mse: 0.0012848956346046268, ridge_rmse: 0.03584544091798324
ridge name:0.026921366994887817 , ridge_mse: 0.0012806614583793406, ridge_rmse: 0.035786330607919845